# -*- coding: utf-8 -*-
"""movie_recommendation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C_O_uLOHXYlzdRrXrFCESUXwGDp5-uCV
"""

from google.colab import files
uploaded = files.upload()

import io
import pandas as pd
import numpy as np


movies = pd.read_csv(io.BytesIO(uploaded['movies.csv']))
ratings = pd.read_csv(io.BytesIO(uploaded['ratings.csv']))

df2 = movies.merge(ratings, on = 'movieId')

df2

adf  = pd.DataFrame(df2.groupby('title')['rating'].mean())
print(adf)

adf['counts'] = df2.groupby('title')['rating'].count()
print(adf)

df4 = pd.DataFrame(df2.pivot_table(index='userId', columns='title', values='rating'))
print(df4)

cdf = pd.DataFrame(df4.corrwith(df4['Shawshank Redemption, The (1994)']))
print(cdf)

cdf.dropna(inplace=True)
print(cdf)

odf = cdf.merge(adf, on = 'title')
odf.columns = ['correlation', 'rating', 'counts']
print(odf)

df6 = odf[odf['counts']>80].sort_values('correlation', ascending=False).head(20)
df7 = df6.merge(movies, on='title')
print(df7)

